### PR TITLE
Announcements sync fix

### LINKED ISSUE #150: AnnouncementActivity crashes for old courses
The `AnnouncementActivity` crashes when trying to open an announcement of an older course like [https://open.sap.com/courses/ml1-1](https://open.sap.com/courses/ml1-1) (11/2017-12/2017).

Might it be the problem, that announcements of older courses are not delivered when querying the API for global announcements? Because the log says that 3 (the announcement count of that course) items have been deleted when opening the viewer Activity. 
For me it seems like a syncing issue.

<details><summary>Log</summary>
```2019-06-16 17:33:51.726 17431-17575/de.xikolo.opensap.debug D/OkHttp: --> GET https://open.sap.com/api/v2/announcements?filter[global]=true
2019-06-16 17:33:52.154 17431-17575/de.xikolo.opensap.debug D/OkHttp: <-- 200 OK https://open.sap.com/api/v2/announcements?filter[global]=true (427ms, unknown-length body)
2019-06-16 17:33:53.895 17431-17536/de.xikolo.opensap.debug I/ListAnnouncementsJob: Announcements received
2019-06-16 17:33:54.158 17431-17536/de.xikolo.opensap.debug D/Sync: DATA: Saved 50 data resources from type Announcement
2019-06-16 17:33:54.185 17431-17536/de.xikolo.opensap.debug D/Sync: DATA: Deleted 3 local resources from type Announcement
2019-06-16 17:33:54.232 17431-17431/de.xikolo.opensap.debug E/REALM_JNI: Row -1006028528 is no longer attached!
2019-06-16 17:33:54.232 17431-17431/de.xikolo.opensap.debug E/REALM_JNI: jni: ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
2019-06-16 17:33:54.233 17431-17431/de.xikolo.opensap.debug E/REALM_JNI: Exception has been thrown: Object is no longer valid to operate on. Was it deleted by another thread?
2019-06-16 17:33:54.236 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547] JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
2019-06-16 17:33:54.236 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at boolean io.realm.internal.UncheckedRow.nativeGetBoolean(long, long) (UncheckedRow.java:-2)
2019-06-16 17:33:54.237 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at boolean io.realm.internal.UncheckedRow.getBoolean(long) (UncheckedRow.java:137)
2019-06-16 17:33:54.238 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at boolean io.realm.de_xikolo_models_AnnouncementRealmProxy.realmGet$visited() (de_xikolo_models_AnnouncementRealmProxy.java:256)
2019-06-16 17:33:54.238 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at void de.xikolo.controllers.announcement.AnnouncementFragment.showAnnouncement(de.xikolo.models.Announcement) (AnnouncementFragment.kt:74)
2019-06-16 17:33:54.239 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at void de.xikolo.controllers.announcement.AnnouncementFragment.access$showAnnouncement(de.xikolo.controllers.announcement.AnnouncementFragment, de.xikolo.models.Announcement) (AnnouncementFragment.kt:23)
2019-06-16 17:33:54.241 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at void de.xikolo.controllers.announcement.AnnouncementFragment$onViewCreated$1.invoke(de.xikolo.models.Announcement) (AnnouncementFragment.kt:58)
2019-06-16 17:33:54.242 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at java.lang.Object de.xikolo.controllers.announcement.AnnouncementFragment$onViewCreated$1.invoke(java.lang.Object) (AnnouncementFragment.kt:23)
2019-06-16 17:33:54.245 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at void de.xikolo.extensions.NonNullMediatorLiveDataKt$observe$2.onChanged(java.lang.Object) (NonNullMediatorLiveData.kt:25)
2019-06-16 17:33:54.245 17431-17431/de.xikolo.opensap.debug A/o.opensap.debu: java_vm_ext.cc:547]   at void androidx.lifecycle.LiveData.considerNotify(androidx.lifecycle.LiveData$ObserverWrapper) (LiveData.java:113)
```</details>

### PR DESCRIPTION
**Pull request by bengelhaupt**
Fixes #150 by loading single `Announcements` off the `/announcements/:id` endpoint instead of loading the entire announcement list.

### CODE REVIEW

File: app/src/main/java/de/xikolo/network/jobs/GetAnnouncementJob.kt [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import ru.gildor.coroutines.retrofit.awaitResponse
+
+class GetAnnouncementJob(private val announcementId: String, networkState: NetworkStateLiveData, userRequest: Boolean) : NetworkJob(networkState, userRequest) {
+
+    companion object {
+        val TAG: String = GetAnnouncementJob::class.java.simpleName
+    }
+
+    override suspend fun onRun() {
+        val response = ApiService.instance.getAnnouncement(announcementId).awaitResponse()
```
Comment (bengelhaupt) [inline app/src/main/java/de/xikolo/network/jobs/GetAnnouncementJob.kt]: Should this only be executed when the user is logged in? Actually not, but what about a logged-out user trying to load a course announcement?
